### PR TITLE
Replace &nbsp; with a space

### PR DESCRIPTION
**Pull request by armujahid**
Remove undesirable non-breaking spaces i.e &nbsp;

### CODE REVIEW

**Comment by armujahid** [comment]
You are right. &nbsp; should be replaced with a space.
I want to download invisible rows because they are part of table and are temporarily hidden by pager

**Comment by armujahid** [comment]
But downloading complete table instead of just visible table should be optional. I will make it optional in my next PR. I have reverted that commit for now

**Comment by rubo77** [comment]
You should have rebased your commit, there were four commits in your PR, I had to revert them and squash them into one... done

**Comment by armujahid** [comment]
Thanks

**Pull request merged**
